### ISSUE TITLE
/opt/modulefiles/applications/gnutools and gnutools.t was not created

### ISSUE THREAD

**Issue by kimrojas** [sdsc/gnutools-roll#2]
I'm installing the gnutools-roll for ROCKS 6.2, 
The installed rolls are:
```
NAME         VERSION  ARCH   ENABLED
ganglia:     6.2      x86_64 yes    
kernel:      6.2      x86_64 yes    
web-server:  6.2      x86_64 yes    
python:      6.2      x86_64 yes    
java:        6.2      x86_64 yes    
base:        6.2      x86_64 yes    
perl:        6.2      x86_64 yes    
os:          6.2      x86_64 yes    
sdsc:        master.0 x86_64 yes    
gnucompiler: master.0 x86_64 yes    
gnutools:    master.0 x86_64 yes         (NOT HERE PRIOR TO BUILD/INSTALL)
```

Prior to build, texinfo was installed (by means of rpm download since a "`yum install texinfo`" led to no package error)

[Build.log](https://drive.google.com/file/d/1ZgI1McDY0Gj3EA2wPRwZNZN_DZ1WcP0A/view?usp=sharing) 

/root/rolltests/ directory content:
```
total 12
-rwxr-xr-x 1 root root 5609 Apr  5 20:27 gnucompiler.t
-rw-r--r-- 1 root root    0 Apr  5 23:31 list.log
-rwxr-xr-x 1 root root 1670 Apr  5 01:09 sdsc.t
```
/opt/modulefiles/applications/ content:
```
total 12
drwxr-xr-x 2 root root 4096 Apr  5 23:05 gmp
-rw-r--r-- 1 root root    0 Apr  5 23:32 list.log
drwxr-xr-x 2 root root 4096 Apr  5 21:19 mpc
drwxr-xr-x 2 root root 4096 Apr  5 21:19 mpfr
```

**Comment by jjhayes** [comment]
Sorry for the delay in responding. Most of the SDSC rolls don't install on the front end; in order to do so, you need to ask Rocks for the installation script for a login or compute node. This command, run on the front end, should work with this and other rolls:

% rocks run roll gnutools host=NAME | bash

where NAME is a compute or login node dns name, e.g., "compute-0-0".

I've updated the README.md file to discuss this.

Jim
